### ISSUE TITLE
Update Demo with better examples

### ISSUE THREAD

**Issue by anilmaurya** [anilmaurya/ember-inplace-edit#4]

**Comment by sherpalabsio** [comment]
I think for a start we could use the test/dummy app somehow. I like to use it during the plug-in development, we could pimp it up with code examples, tabs etc...

**Comment by anilmaurya** [comment]
@tothpeter Agreed. Copying test/dummy to `gh-branch` will be good start.

**Comment by sherpalabsio** [comment]
How do you imagine it exactly?

How about: we use the final files from the dist folder from the dummy app, so we only have to maintain it only one place. If I am not mistaken the current demo works similar, it uses the production build of a demo ember app.

**Comment by anilmaurya** [comment]
Yes, current demo is production build of ember app.

I meant to copy build of dummy app.

**Comment by sherpalabsio** [comment]
I uploaded a new version of demo page, check this out:  http://anilmaurya.github.io/ember-inplace-edit/
What do you think?

**Comment by anilmaurya** [comment]
Awesome Job 🏆 . Thank you.
